In [9]:
import numpy as np
# Define two 3x3 matrices
A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])
B = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])
# i. Inverse of matrix A
inverse_A = np.linalg.inv(A)
print("Matrix A:", A)
print("\nMatrix B:", B)
print("\nInverse of Matrix A:", inverse_A)
# ii. Determinant of matrix B
det_B = np.linalg.det(B)
print("\nDeterminant of Matrix B:", det_B)
# iii. Matrix multiplication A.B
result = np.dot(A, B)
print("\nA.B:")
print(result)

Matrix A: [[1 2 3]
 [0 1 4]
 [5 6 0]]

Matrix B: [[2 1 3]
 [1 0 2]
 [4 1 1]]

Inverse of Matrix A: [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Determinant of Matrix B: 6.0

A.B:
[[16  4 10]
 [17  4  6]
 [16  5 27]]


In [2]:
import numpy as np
from scipy.linalg import solve
A = np.array([
    [2, 3],
    [4, 5]
])
B = np.array([8, 14])
solution = solve(A, B)
print("Value of x =", solution[0])
print("Value of y =", solution[1])


Value of x = 1.0
Value of y = 2.0


In [4]:
import numpy as np
# Distance between P and Q
distance = 120
A = np.array([
    [11, -11],
    [1, 1]
])

B = np.array([120, 120])

v1, v2 = np.linalg.solve(A, B)

print("Velocity of Car 1 =", round(v1, 2), "km/h")
print("Velocity of Car 2 =", round(v2, 2), "km/h")

Velocity of Car 1 = 65.45 km/h
Velocity of Car 2 = 54.55 km/h


In [11]:
import numpy as np
import scipy.linalg

#4x4 matrix
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [2, 4, 6, 8],
    [9, 10, 11, 12]
])
# Transpose of matrix
transpose = A.T

# Rank of matrix
rank = np.linalg.matrix_rank(A)

print("Original Matrix:\n", A)

print("\nTranspose of Matrix:\n",transpose)

print("\nRank of Matrix:", rank)

Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  4  6  8]
 [ 9 10 11 12]]

Transpose of Matrix:
 [[ 1  5  2  9]
 [ 2  6  4 10]
 [ 3  7  6 11]
 [ 4  8  8 12]]

Rank of Matrix: 2


In [12]:
import numpy as np
from scipy.linalg import eig
A = np.array([
    [4, 1, 0, 0],
    [1, 3, 0, 0],
    [0, 0, 2, 1],
    [0, 0, 1, 2]
])
eigenvalues, eigenvectors = eig(A)
print("Matrix A:\n",A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n",eigenvectors)

Matrix A:
 [[4 1 0 0]
 [1 3 0 0]
 [0 0 2 1]
 [0 0 1 2]]

Eigenvalues:
 [4.61803399+0.j 2.38196601+0.j 3.        +0.j 1.        +0.j]

Eigenvectors:
 [[ 0.85065081 -0.52573111  0.          0.        ]
 [ 0.52573111  0.85065081  0.          0.        ]
 [ 0.         -0.          0.70710678 -0.70710678]
 [ 0.         -0.          0.70710678  0.70710678]]


In [13]:
import numpy as np
from scipy.linalg import lu
A = np.array([
    [4, 1, 0, 0],
    [1, 3, 0, 0],
    [0, 0, 2, 1],
    [0, 0, 1, 2]
])
P, L, U = lu(A)
print("Matrix A:\n",A)
print("\nP Matrix:\n",P)
print("\nL Matrix:\n",L)
print("\nU Matrix:\n",U)

Matrix A:
 [[4 1 0 0]
 [1 3 0 0]
 [0 0 2 1]
 [0 0 1 2]]

P Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

L Matrix:
 [[1.   0.   0.   0.  ]
 [0.25 1.   0.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.   0.5  1.  ]]

U Matrix:
 [[4.   1.   0.   0.  ]
 [0.   2.75 0.   0.  ]
 [0.   0.   2.   1.  ]
 [0.   0.   0.   1.5 ]]


In [14]:
import numpy as np
from scipy.linalg import qr, svd, lstsq
# Square matrix for QR and SVD
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])
# i. QR Decomposition
Q, R = qr(A)
print("QR Decomposition")
print("Q =\n",Q)
print("R =\n",R)
# ii. SVD
U, S, Vt = svd(A)
print("\nSVD")
print("U =\n",U)
print("Singular Values =\n",S)
print("V Transpose =\n",Vt)
# iii. Least Squares (LSC)
A2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
b = np.array([5, 11, 17])
x, residuals, rank, singular_values = lstsq(A2, b)
print("\nLeast Squares Solution")
print("Solution =", x)
print("Residuals =", residuals)
print("Rank =", rank)
print("Singular Values =", singular_values)

QR Decomposition
Q =
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R =
 [[ -8.1240384   -9.6011363  -11.93987462]
 [  0.           0.90453403   1.50755672]
 [  0.           0.           0.40824829]]

SVD
U =
 [[-0.20933734  0.96438514  0.16167618]
 [-0.50384851  0.03532145 -0.86306956]
 [-0.8380421  -0.26213299  0.47850992]]
Singular Values =
 [17.41250517  0.87516135  0.19686652]
V Transpose =
 [[-0.46466755 -0.55375455 -0.69097031]
 [-0.83328635  0.00949949  0.55275999]
 [ 0.2995295  -0.83262576  0.46585022]]

Least Squares Solution
Solution = [1. 2.]
Residuals = 1.1792752123721947e-32
Rank = 2
Singular Values = [9.52551809 0.51430058]
